name: variants2genes # name of environment
channels:
- bioconda
- default
dependencies:             # everything under this, installed by conda
- parallel
- vcflib
- bedtools
- samtools
- bcftools
- tabix
- sra-tools
- ncbi-ngs-sdk
- hisat2
- r-ggplot2
- r-reshape2
- r-dplyr
- r-gridextra
